import {
  IsArray,
  IsBoolean,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  ValidateNested,
  validateSync,
} from "#class-validator";
import { plainToInstance, Type } from "#class-transformer";

/**
 * One row in the persisted terms-wizard answers. The customer-facing quote
 * page reads these straight off the quote — no need to re-walk the
 * conversation to know the agreed payment / warranty / etc. terms.
 */
export interface QuoteTerm {
  /** Step id from TERMS_WIZARD_V1 (e.g. "payment_terms"). */
  stepId: string;
  /** Human label of the step (e.g. "Payment terms"). */
  label: string;
  /** Resolved value the customer agreed to (e.g. "30 / 30 / 40"). */
  value: string;
}

export class LineItemDto {
  @IsString()
  description!: string;

  @IsNumber()
  quantity!: number;

  @IsString()
  unit!: string;

  /** Per-unit price in INTEGER CENTS. Line total is price * quantity. */
  @IsNumber()
  price!: number;
}

export class CreateQuoteDto {
  @IsOptional()
  @IsString()
  customerId?: string;

  @IsString()
  summary!: string;

  /** Short, three-words-or-less label used as the human-readable job title
   *  in headings, the in-chat card, email subject, SMS body, and agreement
   *  hero. Generated by the polish-job-details LLM step; falls back to
   *  `summary` when missing. */
  @IsOptional()
  @IsString()
  jobName?: string;

  /** Polished narrative produced from the user's raw job description.
   *  Rendered on the quote preview, the customer-facing quote email,
   *  and rendered on the public quote page's jobDetails. */
  @IsOptional()
  @IsString()
  description?: string;

  /** Per-language cache of the job-details description, keyed by lang code
   *  (e.g. { en, es }). Populated lazily — a language is translated the first
   *  time the quote is previewed/sent in it. Readers render
   *  descriptionByLang[lang] ?? description. */
  @IsOptional()
  @IsObject()
  descriptionByLang?: Record<string, string>;

  /** Per-language job title + summary (keyed by lang code), so the customer's
   *  agreement renders the heading in their language too. Populated from the
   *  picked job option's translations. */
  @IsOptional()
  @IsObject()
  jobNameByLang?: Record<string, string>;

  @IsOptional()
  @IsObject()
  summaryByLang?: Record<string, string>;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => LineItemDto)
  lineItems!: LineItemDto[];

  /** Total quote value in INTEGER CENTS. Audit1 #3 unified the money
   *  schema so dollars-as-floats no longer cross any boundary. */
  @IsOptional()
  @IsNumber()
  estimatedTotal?: number;

  @IsOptional()
  @IsString()
  status?: string;

  /** Onboarding "see what your customer sees" sample (EnsureSampleQuote).
   *  Sample quotes render as a badged card but contribute to NO pipeline,
   *  money, or open-tracking aggregate (P-15). */
  @IsOptional()
  @IsBoolean()
  isSample?: boolean;

  /** Captured terms-wizard answers (payment/warranty/etc.). Persisted while
   *  drafting so the public quote page renders them as the agreement's
   *  numbered Terms — the quote IS the agreement. */
  @IsOptional() @IsArray()
  terms?: QuoteTerm[];
  @IsOptional() @IsString()
  effectiveDate?: string;
  @IsOptional() @IsString()
  startDate?: string;
  @IsOptional() @IsString()
  estimatedCompletionDate?: string;

  @IsOptional() @IsString()
  sentAt?: string;
  @IsOptional() @IsString()
  acceptedAt?: string;
  @IsOptional() @IsString()
  lostAt?: string;
  @IsOptional() @IsString()
  acceptedSignature?: string;
  @IsOptional() @IsString()
  acceptedName?: string;
  /** Masked TIN captured at the signature ceremony (last 4 only). */
  @IsOptional() @IsString()
  acceptedTinMasked?: string;
  /** Idempotency stamp: the accepted-confirmation (milestone billing +
   *  customer receipt) already ran for this acceptance. */
  @IsOptional() @IsString()
  acceptedNotifiedAt?: string;
  @IsOptional() @IsString()
  declineReason?: string;
  @IsOptional() @IsString()
  declineNote?: string;
  @IsOptional() @IsString()
  declinedName?: string;
}

export class UpdateQuoteDto {
  @IsOptional() @IsString()
  customerId?: string;
  @IsOptional() @IsString()
  summary?: string;
  @IsOptional() @IsString()
  jobName?: string;
  @IsOptional() @IsString()
  description?: string;
  @IsOptional() @IsObject()
  descriptionByLang?: Record<string, string>;
  @IsOptional() @IsObject()
  jobNameByLang?: Record<string, string>;
  @IsOptional() @IsObject()
  summaryByLang?: Record<string, string>;
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => LineItemDto)
  lineItems?: LineItemDto[];
  /** INTEGER CENTS. */
  @IsOptional() @IsNumber()
  estimatedTotal?: number;
  @IsOptional() @IsString()
  status?: string;
  @IsOptional() @IsArray()
  terms?: QuoteTerm[];
  @IsOptional() @IsString()
  effectiveDate?: string;
  @IsOptional() @IsString()
  startDate?: string;
  @IsOptional() @IsString()
  estimatedCompletionDate?: string;
  @IsOptional() @IsString()
  sentAt?: string;
  @IsOptional() @IsString()
  acceptedAt?: string;
  @IsOptional() @IsString()
  lostAt?: string;
  @IsOptional() @IsString()
  acceptedSignature?: string;
  @IsOptional() @IsString()
  acceptedName?: string;
  @IsOptional() @IsString()
  acceptedTinMasked?: string;
  @IsOptional() @IsString()
  acceptedNotifiedAt?: string;
  @IsOptional() @IsString()
  declineReason?: string;
  @IsOptional() @IsString()
  declineNote?: string;
  @IsOptional() @IsString()
  declinedName?: string;
}

export interface Quote extends CreateQuoteDto {
  id: string;
  /** Owner. Populated server-side from the auth context — never accept from request body. */
  userId: string;
  createdAt: string;
  updatedAt: string;
}

export type QuoteStage =
  | "draft"
  | "sent"
  | "opened"
  | "cooling"
  | "stale"
  | "won"
  | "lost";

/**
 * Quote row enriched with the derived stage + engagement signal the /quotes
 * card consumes. Computed by `BuildQuoteCards`; never persisted.
 */
export interface QuoteCard extends Quote {
  stage: QuoteStage;
  daysIn: number;
  opens: number;
  lastOpenAt: string | null;
  sentDays: number | null;
  decidedDays: number | null;
  customerName: string | null;
}

export interface QuoteOpenEntry {
  at: string;
  atRel: string;
  device: "desktop" | "mobile" | "tablet" | "unknown";
  durationMs?: number;
}

export interface QuoteOpensResponse {
  opens: QuoteOpenEntry[];
}

export function parseCreateQuote(input: unknown): CreateQuoteDto {
  const dto = plainToInstance(CreateQuoteDto, input);
  const errors = validateSync(dto);
  if (errors.length) {
    throw new Error(`invalid quote: ${JSON.stringify(errors)}`);
  }
  return dto;
}

export function parseUpdateQuote(input: unknown): UpdateQuoteDto {
  const dto = plainToInstance(UpdateQuoteDto, input);
  const errors = validateSync(dto);
  if (errors.length) {
    throw new Error(`invalid quote patch: ${JSON.stringify(errors)}`);
  }
  return dto;
}
